### PR TITLE
Added some fluent-api extensions

### PR DESCRIPTION
**Pull request by lwuckel**
Added some fluent api extension

#### Details

With this changes you can define Given-When-Then in an easy readable way.

For instance Scene_Fluent_Tests.cs

`this.Runner
  .Given(Given_A)
  .When(B)
  .Then(C)
  .Run();`

Or if you want to use context SceneContext_Fluent_tests.cs

`new ActionTestContext(this.Runner)
  .Given.A
  .When.B(5)
  .Then.C
  .Run();`

Every test-method can now have an Output-Attribute 
For instance

`[Given("description test")]
void Given_A()
{
}`

List of changes:

+Added fluent api for simple test-definitions (Scene.cs)
+Added fluent api for complex test-definitions (SceneContext.cs)
+Added Attributes to define the output report text

#### Checklist
- [ ] Changes are backward compatible with previous version of Core and Framework,
- [ ] Changelog has been updated,
- [x] Debugging experience is good,
- [x] Examples have been updated to present new feature (if applicable),
- [ ] Example reports have been updated in examples\ExampleReports directory (if applicable)

### CODE REVIEW

**Comment by Suremaker** [comment]
Hello @lwuckel,
Thanks for the PR. For the next few days I will be focused on putting LightBDD 3.0 together, but before the release I will come back to this PR and review if to include it in the main LightBDD code or keep it as an addon. No matter of the outcome I'll ensure that you will be able to use it that way in LightBDD 3.0.

**Comment by Suremaker** [comment]
Hello @lwuckel ,

As LightBDD 3.0 is out I can take a look at this PR.

I see you have introduced a new way of defining scenarios. As LightBDD offers currently a set of variations how steps can be defined, please describe how this new approach is better than others and what values it offers that others do not provide.

By looking at the sample notion, I believe that currently you can achieve the same outcome by using one of the following allowed syntax:

[Basic syntax](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#basic-scenarios):
```c#
Runner.RunScenario(
  Given_some_criteria,
  When_I_perform_some_action,
  When_I_perform_some_other_action,
  Then_I_should_get_some_outcome
);
```

[Extended syntax](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#extended-scenarios) with separated G/W/T:
```c#
Runner.RunScenario(
  given => Some_criteria(),
  when => I_perform_some_action(),
  and => I_perform_some_other_action(),
  then => I_should_get_some_outcome()
);
```

[Extended syntax](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#extended-scenarios) with G/W/T being part of method:

```c#
Runner.RunScenario(
  _ => Given_some_criteria(),
  _ => When_I_perform_some_action(),
  _ => When_I_perform_some_other_action(),
  _ => Then_I_should_get_some_outcome()
);
```

[Compact syntax](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#compact-scenarios) if you prefer to write textual descriptions:

```c#
await Runner
  .AddStep("Given some criteria", () => /* code */)
  .AddStep("When I perform some action", () => /* code */)
  .AddStep("And I perform some other action", () => /* code */)
  .AddStep("Then I should get some outcome", () => /* code */)
  .RunAsync();
```

Actually, it is possible also to use fluent version of `AddStep` with any of the above syntax as well and write test like:
```c#
await Runner
  .AddStep(Given_some_criteria),
  .AddStep(When_I_perform_some_action)
  .AddStep(When_I_perform_some_other_action)
  .AddStep(Then_I_should_get_some_outcome);
```
... if desired, or any other combination of the above variations.

All of the above examples will render similarly, where second WHEN will be transformed to AND (that is why LightBDD does not explicitly expose any methods called `And()`, as such transformation is automatic if needed, while customizable if needed: [wiki page](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#steps-auto-grouping)).

An another point is that I am planning to extend Runner with more capabilities like specifying setup/teardowns (https://github.com/LightBDD/LightBDD/issues/143) that I presume will have to be implemented here as well...

**Comment by lwuckel** [comment]
Hi @Suremaker 

you are right. I  can write the steps in this way

```
Runner.RunScenario(
  Given_some_criteria,
  When_I_perform_some_action,
  When_I_perform_some_other_action,
  Then_I_should_get_some_outcome
);

```

But it is possible to write this too:

```
Runner.RunScenario(
  When_I_perform_some_action,
  Given_some_criteria,
  Then_I_should_get_some_outcome
  When_I_perform_some_other_action,
);

```

The steps are not in the right order. So maybe the tests will fail.

With the new approach this is not possible, because the API don't allow this.
You only can write this

```
Runner
  .Given(some_criteria)
  .When(I_perform_some_action)
  .When(I_perform_some_other_action)
  .Then(I_should_get_some_outcome)
  .Run();

```

So every developer in a group has to follow this order (Given, When, Then)
To make it clear which method should be used in which step you can use the GivenAttribute, WhenAttribute and ThenAttribute.


If you need more flexibility in complex scenarios then you can use the other API where you have to define classes for every step group (givens, whens, thens).

```
new ActionTestContext(this.Runner) 
   .Given.some_criteria 
   .When.I_perform_some_action(5) 
   .Then.I_should_get_some_outcome 
   .Run();
```

The ActionTestContext (derived from SceneContext) is only an example to define the given-class, the when-class and the then-class.
So every step is grouped by an own class.

With this new API 

- you are saved for the right execution order
- code review is easier, because developers can't mix the methods like they want
- you don't need to deal with prefix-names for method-names like "Given_"
- you don't need lamdas
- you can use properties and methods
- every method can define it's own output text by using the Attributes


You are right that with the existing API I have the freedom to write the scenario test in every way. 
But in developer groups it's maybe not a good way that everybody can go an own way. 
There has to be restrictions so that it's not so easy to make mistakes.


My code is not perfect, but maybe good approach to prevent for mistakes.

Regards Lars

**Comment by Suremaker** [comment]
Hello Lars,

Thanks for the response with the explanation. I understand now the reasoning beyond the change.

> You are right that with the existing API I have the freedom to write the scenario test in every way.
> But in developer groups it's maybe not a good way that everybody can go an own way.
> There has to be restrictions so that it's not so easy to make mistakes.

I see your point now. The LightBDD does not enforce you to use any explicit order of the steps, or to follow strict Given-When-Then keywords, which means that you can write scenarios like:
* Given_some_criteria, When_I_perform_action, Then_I_should_get_outcome,
* When_I_perform_action, Then_I_should_get_outcome
* Given_some_criteria, When_I_perform_action, Then_I_should_get_outcome, When_I_do_something_additional, Then_my_outcome_should_change
* Do_this, Do_that, Assert_this (i.e. no keywords at all).

The logic beyond that is that I cannot predict all the use cases that users of the library would like to create, so I am giving them a free hand, leaving the style of the tests up to them and their review processes. Having said that, LightBDD could get extended with a feature that will verify the test scenario structure upon execution, encouraging devs to follow some accepted patterns... 

... but let me first go through your points...

I have created a following sample:

```c#
public class My_feature : FeatureFixture
{
    private List<string> _list;

    [Scenario]
    public void My_simple_scenario()
    {
        Runner.Given(Some_criteria)
            .When(I_perform_some_action)
            .When(I_perform_some_other_action)
            .Then(I_should_get_some_outcome)
            .Run();
    }

    [Then]
    private void I_should_get_some_outcome()
    {
        Assert.That(_list, Is.EqualTo(new[] { "foo", "bar", "baz" }));
    }

    [When]
    private void I_perform_some_other_action()
    {
        _list.Add("baz");
    }

    [When]
    private void I_perform_some_action()
    {
        _list.Add("bar");
    }

    [Given]
    private void Some_criteria()
    {
        _list = new List<string> { "foo" };
    }
}
```

When executed, I got following outcome:
```
SCENARIO: My simple scenario
  STEP 1/4: GIVEN Some criteria...
  STEP 1/4: GIVEN Some criteria (Passed after 16ms)
  STEP 2/4: WHEN I perform some action...
  STEP 2/4: WHEN I perform some action (Passed after <1ms)
  STEP 3/4: AND I perform some other action...
  STEP 3/4: AND I perform some other action (Passed after <1ms)
  STEP 4/4: THEN I should get some outcome...
  STEP 4/4: THEN I should get some outcome (Passed after 30ms)
  SCENARIO RESULT: Passed after 77ms
```

> you are saved for the right execution order
> code review is easier, because developers can't mix the methods like they want

I see the point here of having a fluent interface expecting you to start with `Given`s, followed by `When`s and `Then`s.  

However with the new API I can write this:
```c#
[Scenario]
public void My_simple_scenario()
{
    Runner.Given(Some_criteria)
        .When(I_should_get_some_outcome)
        .Then(I_perform_some_other_action)
        .Then(I_perform_some_action)
        .Run();
}
```
... which renders like this:
```
SCENARIO: My simple scenario
  STEP 1/4: GIVEN Some criteria...
  STEP 1/4: GIVEN Some criteria (Passed after 17ms)
  STEP 2/4: THEN I should get some outcome...
  STEP 2/4: THEN I should get some outcome (Failed after 90ms)
  SCENARIO RESULT: Failed after 140ms
    Step 2: NUnit.Framework.AssertionException :   Expected is <System.String[3]>, actual is <System.Collections.Generic.List`1[System.String]> with 1 elements
    	  Values differ at index [1]
    	  Missing:  < "bar", "baz" >
    	at Example.LightBDD.NUnit3.My_feature.I_should_get_some_outcome() in D:\dev\LightBDD\examples\Example.LightBDD.NUnit3\My_feature.cs:line 26
    	at LightBDD.Framework.Scenarios.Implementation.BasicStepCompiler.StepExecutor.Execute(Object context, Object[] args) in D:\dev\LightBDD\src\LightBDD.Framework\Scenarios\Implementation\BasicStepCompiler.cs:line 90
```
image

Please take a look at the mismatch of the keywords...

Of course this one is pretty drastic example, but there can be a more subtle one, that will still end up with mismatch:
```c#
[Scenario]
public void My_simple_scenario()
{
    Runner.Given(Some_criteria)
        .When(I_perform_some_action)
        .Then(I_perform_some_other_action)
        .Then(I_should_get_some_outcome)
        .Run();
}
```
and
```
SCENARIO: My simple scenario
  STEP 1/4: GIVEN Some criteria...
  STEP 1/4: GIVEN Some criteria (Passed after 16ms)
  STEP 2/4: WHEN I perform some action...
  STEP 2/4: WHEN I perform some action (Passed after <1ms)
  STEP 3/4: AND I perform some other action...
  STEP 3/4: AND I perform some other action (Passed after <1ms)
  STEP 4/4: THEN I should get some outcome...
  STEP 4/4: THEN I should get some outcome (Passed after 26ms)
  SCENARIO RESULT: Passed after 74ms
```

The report does not really reflect the scenario.

> you don't need to deal with prefix-names for method-names like "Given_"

Let's take a look at the previous issue again. Actually, if I would have my steps starting with prefixes, it will be obvious that there is something wrong with this scenario:
```c#
[Scenario]
public void My_simple_scenario()
{
    Runner.Given(Given_some_criteria)
        .When(When_I_perform_some_action)
        .Then(When_I_perform_some_other_action)
        .Then(Then_I_should_get_some_outcome)
        .Run();
}
```

But ultimately, I believe the bottom line is in the steps themselves.  
The `given`, `when`, `then` step types have specific meaning, thus different implementation:
* given - it is a setup of the scenario and system under test,
* when - it is an action that we are executing on the system under test,
* then - it is an outcome that we expect to get (assertions).

It actually means that the step implementation is what decides more if the step is setup, action or assertion type (G/W/T).

Because of the above reasoning, I am always adding those prefixes to the steps I am working on, as it is more clear on what exactly the step method is doing. It is also easier to browse through the methods when writing tests and easier to review the code.  
Then, it is however a question what is easier to read:
```c#
[Scenario]
public void My_simple_scenario()
{
    Runner.Given(Given_some_criteria)
        .When(When_I_perform_some_action)
        .Then(When_I_perform_some_other_action)
        .Then(Then_I_should_get_some_outcome)
        .Run();
}
```
or
```c#
[Scenario]
public void My_simple_scenario()
{
    Runner.RunScenario(
        Given_some_criteria,
        When_I_perform_some_action,
        When_I_perform_some_other_action,
        Then_I_should_get_some_outcome);
}
```

> you don't need lamdas

True. But with basic scenario syntax you also do not need lambdas. Lambdas have been introduced to properly render parameterized scenarios like this one:

```c#
public class My_calculator_feature : FeatureFixture
{
    private Calculator _calc;
    private int _result;

    [Scenario]
    public void Adding_numbers()
    {
        Runner.RunScenario(
            _ => Given_calculator(),
            _ => When_I_add_X_and_Y(3, 5),
            _ => Then_I_should_get_RESULT(8)
        );
    }

    private void Given_calculator()
    {
        _calc = new Calculator();
    }

    private void When_I_add_X_and_Y(int x, int y)
    {
        _result = _calc.Add(x, y);
    }

    private void Then_I_should_get_RESULT(int result)
    {
        Assert.That(_result, Is.EqualTo(result));
    }
}
```
```
SCENARIO: Adding numbers
  STEP 1/3: GIVEN calculator...
  STEP 1/3: GIVEN calculator (Passed after 16ms)
  STEP 2/3: WHEN I add "3" and "5"...
  STEP 2/3: WHEN I add "3" and "5" (Passed after 1ms)
  STEP 3/3: THEN I should get "8"...
  STEP 3/3: THEN I should get "8" (Passed after 21ms)
  SCENARIO RESULT: Passed after 99ms
```

I did not see a full example on how the fluent GWT api handles parameterized steps. 
Can you please provide one for example for: `new ActionTestContext(this.Runner) .Given.A .When.B(5) .Then.C .Run();` ?

> you can use properties and methods

Can you please provide an example of using properties in `Runner.Given(Property)` and `new ActionTestContext(this.Runner) .Given.A` scenarios and how will they render upon execution?

> every method can define it's own output text by using the Attributes

Can you please give an example when custom output will be beneficial? I guess it may be for some cases where rich text (with punctuation) is expected.. Is it a case?

I have wondered about it the long time ago, but decided not to implement it on purpose, because of the 2 following reasons:

**Readability**:

Assuming I wrote scenario like that:
```c#
[Scenario]
public void My_simple_scenario()
{
    Runner.Given(Some_criteria)
        .When(I_perform_some_action)
        .Then(I_perform_some_other_action)
        .Then(I_should_get_some_outcome)
        .Run();
}
```
It could be pretty confusing to see the output like this:
```
SCENARIO: My simple scenario
  STEP 1/4: GIVEN this is some given description...
  STEP 1/4: GIVEN this is some given description (Passed after 16ms)
  STEP 2/4: WHEN some other description...
  STEP 2/4: WHEN some other description (Passed after <1ms)
  STEP 3/4: AND my when description...
  STEP 3/4: AND my when description (Passed after <1ms)
  STEP 4/4: THEN some assertions...
  STEP 4/4: THEN some assertions (Passed after <1ms)
  SCENARIO RESULT: Passed after 45ms
```
with steps:
```c#
[Given("this is some given description")]
private void Some_criteria(){}

[When("my when description")]
private void I_perform_some_other_action(){}

[When("some other description")]
private void I_perform_some_action(){}

[Then("some assertions")]
private void I_should_get_some_outcome(){}
```

The ability to redefine step will make a discrepancy between the scenario definition and it's outcome, as by reading the scenario code there will be no way to see how does it really look.  
Not having such ability will enforce people to properly name step methods, making them self-describing, and scenario more readable.

**Maintenance**:

Of course the above could be mitigated by ensuring that description is in sync with method name, but it will require much more effort. 
More over, any refactoring done on the step method name will introduce this discrepancy again making inconsistencies on the bigger project pretty quickly.

I am looking forward to reading your thoughts on this,
Cheers,
Wojtek

**Comment by lwuckel** [comment]
Hi Wojtek,

wow. That was a really long comment. :-)

First you are right that when you use the Attributes (e.g. GivenAttribute) you can make the report wrong in the same way like I would write this :

```
[Scenario]
public void My_simple_scenario()
{
    Runner.RunScenario(
        Given_some_criteria,
        Then_I_should_get_some_outcome,
        When_I_perform_some_action,
        When_I_perform_some_other_action
);
}
```

The advantage of the new API would be that I see in the report that someone used explicitly wrong methods. In the code review I only can guess that the methods are used with the wrong purpose.

```
[Scenario]
public void My_simple_scenario()
{
    Runner.Given(Given_some_criteria)
        .When(I_perform_some_action)
        .Then(I_perform_some_other_action)
        .Then(I_should_get_some_outcome)
        .Run();
}
```

If you don't need such report verification then you don't have to use the attributes. Then the report Shows GWT Output like the method names (Given …).


It's true, that with the current API you have the freedom to implement every need. But I think your API is missing a way to force the way that the developer has to go.

It's clear that I can't prevent the developer from writing bad code. So if the developer descides to implement an Assert into the given method I can't prevent this ;-)


But your are right I could integrate the verification that a given method is only allowed to have a GivenAttribute and so on. Like an Assertion. But this would only be visible first at runtime. :-(


> Let's take a look at the previous issue again. Actually, if I would have my steps starting with prefixes, it will be obvious that there is something wrong with this scenario:

You are right. If you know the order of GWT then everything is fine. But there is no need to do the order.
With the prefix you only tag the methods for their purpose.

> Because of the above reasoning, I am always adding those prefixes to the steps I am working on, as it is more clear on what exactly the step method is doing. It is also easier to browse through the methods when writing tests and easier to review the code.

Prefixes are conventions that you have to know and that you have to write always in the same way.

```
[Scenario]
public void My_simple_scenario()
{
    Runner.RunScenario(
        GVEN_some_criteria,
        hTen_I_should_get_some_outcome,
        Wenn_I_perform_some_action,
        WN_I_perform_some_other_action
);
}
```

So in a code review I have to verify the writing of the prefix because it's a convention.
Without the prefix it looks (maybe ;-)   ) so:

```
[Scenario]
public void My_simple_scenario()
{
    Runner.Given(Given_some_criteria)
        .When(I_perfrom_sme_action)
        .Then(I_Prform_some_otter_action)
        .Then(I_shold_get_some_outcme)
        .Run();
}
```

It's ugly too. :-) 
But there is no (developer) convention defect.


> Can you please give an example when custom output will be beneficial? I guess it may be for some cases where rich text (with punctuation) is expected.. Is it a case?

Here one example that maybe is needed sometimes in the report as additional Information:

```
[Then("The value should be 1!  (see http://www.google.de)")]
[Given("Call / Read the File C:\kdkdkd.txt")]
```

For the comlex example I first need a coffee ;-)

**Comment by lwuckel** [comment]
> Can you please provide an example of using properties in Runner.Given(Property) and new ActionTestContext(this.Runner) .Given.A scenarios and how will they render upon execution?

In the basic Given-method you can't use properties. Thats right.
But if you use a SceneContext then you can create very complex scenarios.
I think there are situation for easy writing tests like `Given(....).When(...).Then(...).Run()`
But there are more complicated situations where you want to group functionality. Then you could use the SceneContext. There you can define complex given-methods. Only the Given methods are provided and it is forced that after a given-method can only be called another given-method or a when-method and so on.

You could write some methods for a given functionality that is grouped behind one given-method

Here an easy example:

```
	[TestFixture]
	[Description("")]
	[Category("LightBDD")]
	[ScenarioCategory("SceneContext-Kategorie")]
	public class SceneContext_Fluent_tests : FeatureFixture
	{
		[Test]
		[Scenario]
		[Label(nameof(Test))]
		public void Test()
		{
			new ActionTestContext(this.Runner)
				.Given.A
				.When.B(5)
				.Then.C
				.Run();
		}

		class ActionTestContext : SceneContext<Givens, Whens, Thens, Action>
		{
			public ActionTestContext(IBddRunner runner)	: base(null, null, null, a => runner.Given(a))
			{
				Init(new Givens(), new Whens(), new Thens());
			}
		}

		class Givens
		{
			[Given("ok")]
			void Given_A()
			{
			}
			public GivenResult<Givens, Whens> A => ActionTestContext.CreateGiven(Given_A);
		}
		class Whens
		{
			int i;

			void When_B()
			{
			}
			public WhenResult<Whens, Thens> B(int i)
			{
				this.i = i;
				return ActionTestContext.CreateWhen(When_B);
			}
		}

		class Thens
		{
			void Then_C()
			{
			}

			public ThenResult<Thens, Action> C => ActionTestContext.CreateThen(Then_C);
		}
	}

```

Both APIs are only wrappers to the standard step call.

The reason for this extensions are only to extend the possibilities of your framework. Not to replace something.

I believe that there are needs for freedom in implementation. So that one developer can write fast BDD tests. But there is also a need for more strictlyness.

So you could provide both.


Cheers to you :-)

Lars

**Comment by Suremaker** [comment]
Hello Lars, sorry for being quiet. I had busy few days and just popped up here to fix bug on 3.0. Will come back to this PR by tomorrow.

**Comment by Suremaker** [comment]
Hello @lwuckel ,

Thanks for the response. I thought about this change and here are my thoughts:

Let me first refer to your last comment:
> I believe that there are needs for freedom in implementation. So that one developer can write fast BDD tests...

I totally agree with you here. LightBDD is "light" because it offers a lightweight layer on top of the beloved test frameworks, helping to write tests in more behavioral manner. Hovewer, it is also made with extensibility in mind.  

When I created version 2.x I explicitly created LightBDD.Core and LightBDD.Framework as two separate projects, to ensure framework extensibility. Together with `IBddRunner` interface, it allowed me to create various styles of defining scenarios (basic, extended syntax, fluent interface, sync/async steps as well as composites and contextual scenarios).  
Just few versions ago, in 2.5.0, I introduced [compact scenario syntax](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#compact-scenarios) to 
fulfil needs for creating more unit-test like scenarios :smiley: .

The maintenance of such wide api costs however and brings complexity (like ensuring the report is in sync with the code :wink: ), that is why I prefer to introduce the new way of doing things only if there is currently no way of achieving the same in the library.

Because of the above I decided not to include your change in the main repo, with following reasons:
* there are already 2 options for specifying given/when/then keywords, the [lambda one](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#extended-scenarios) (supported in extended syntax) and [prefix one](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#steps-auto-grouping) (supported by every syntax),
* there is an existing [fluent interface](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#fluent-scenarios), allowing to compose scenarios of various number of steps or step types. It is used also to define [composite steps](https://github.com/LightBDD/LightBDD/wiki/Composite-Steps-Definition) by the way,
* regarding complex scenarios, there is already a support for [contextual scenarios and steps](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#contextual-scenarios) and it's integrated with [DI](https://github.com/LightBDD/LightBDD/wiki/DI-Containers#using-di-containers-in-contextual-scenarios). I have presented an example implementation of complex contexts on Gitter today (here is the [gist to it](https://gist.github.com/Suremaker/10b2f05c844fe2e657f74b647a7074be)).

**Having said that, please feel free to create a project with your extension and I will be happy to link it form the LightBDD project page**. Actually you can achieve that without any modifications of the LightBDD.Core nor the Framework (I'll put the details at the end of the post).

----

Before I jump to the details of the implementation, let me comment on two more things:

> It's true, that with the current API you have the freedom to implement every need. But I think your API is missing a way to force the way that the developer has to go.
> [...]
> But your are right I could integrate the verification that a given method is only allowed to have a GivenAttribute and so on. Like an Assertion. But this would only be visible first at runtime. :-(
> [...] But there is also a need for more strictlyness.

By showing that even with your new API it is possible to mix up the order of Given/When/Thens I wanted to highlight that there is no easy way to actually do it right without over-complicating things.  
I guess one of the option could be to write Roslyn Analyzer that would check if actions used in `.Given()` method have `[Given]` attribute. Perhaps you could try it...

However, if there is a need to "encourage" developers to write GWTs properly, I can actually extend LightBDD with opt-in feature that would be checking it at the runtime. The runtime check is not that great like compilation one, but actually it would work for *all* scenarios written in any style. Let me make a ticket for it.

> Here one example that maybe is needed sometimes in the report as additional Information:
> [Then("The value should be 1!  (see http://www.google.de)")]
> [Given("Call / Read the File C:\kdkdkd.txt")]

This can be achieved today by using [step comments](https://github.com/LightBDD/LightBDD/wiki/Step-Comments), that are integrated with runner and the reports. The commenting feature is designed to provide additional information about executed step.

-------------

Ok, back to the extensions...  
If you would be interested in making your extension project, you can implement the custom step names by using methods exposed by [compact syntax](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#compact-scenarios).

Here is a SceneExtensions class implemented with 3.0.1 version of LightBDD.Framework (i.e. no changes to `NameParser.cs`):

```c#
/// <summary>
/// Extention methods for Given-When-Then
/// </summary>
public static class SceneExtensions
{
    /// <summary>
    /// Given Extention for IBddRunner 
    /// </summary>
    /// <param name="runner">Test-Runner</param>
    /// <param name="given">Test-Action to be executed</param>
    /// <returns>Given-object</returns>
    public static IGiven<Action> Given(this IBddRunner runner, Action given)
    {
        return new Scene<Action>(runner)
            .Given(given);
    }

    /// <summary>
    /// Run the definition of the SceneContext.
    /// <see cref="SceneContext{TGiven, TWhen, TThen, TFunc_Given}"/>
    /// Execute the steps
    /// </summary>
    /// <typeparam name="TThen">Type of then-methods class</typeparam>
    /// <param name="then">ThenResult object</param>
    public static void Run<TThen>(this ThenResult<TThen, Action> then)
    {
        var scene = (Scene<Action>)then.To();
        RunScene(scene);
    }

    /// <summary>
    /// Run the definition of the Scene
    /// <see cref="Scene{TAction}"/>
    /// </summary>
    /// <param name="then">Then-object</param>
    public static void Run(this IThen<Action> then)
    {
        var scene = (Scene<Action>)then;
        RunScene(scene);
    }

    private static void RunScene(Scene<Action> scene)
    {
        var integration = scene.Runner.Integrate();
        var provider = new NameProvider(integration.Core.Configuration);
        foreach (var action in scene.End())
        {
            integration.AddStep(
                provider.GetStepName(action.GetMethodInfo()),
                _ => action());
        }

        integration.Core
            .WithCapturedScenarioDetailsIfNotSpecified()
            .Build()
            .ExecuteSync();
    }
}

internal class NameProvider
{
    private readonly INameFormatter _formatter;

    public NameProvider(LightBddConfiguration cfg)
    {
        _formatter = cfg.NameFormatterConfiguration().GetFormatter();
    }

    public string GetStepName(MemberInfo member)
    {
        var attr = member.GetCustomAttribute<StepNameAttribute>();
        if (attr == null)
            return _formatter.FormatName(member.Name);

        var description = attr.Description ?? _formatter.FormatName(member.Name);
        return $"{attr.Name} {description}";
    }
}
```

Cheers,
Wojtek

**Comment by lwuckel** [comment]
Hi Wojtek,

my github repo you can find here:
[GWT on github](https://github.com/lwuckel/GWT)

I have to add some informations on the site, but I haven't found time for this.

The nuget package you can find here
[nuget package](https://www.nuget.org/packages/GWT.LightBDD/)

Bye, Lars

**Pull request closed without merging**
